#!/usr/bin/env python3
"""Versioned manifest queue contract for safe Writer cutovers.

Queued manifests can outlive the Writer that created them. This module stamps
buffer entries with explicit factory identity and dequeues only entries compatible
with the currently-required Writer/certification version. It is provider-free.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shutil
import sys
from typing import Any, Mapping

SCHEMA = "content-render-queue-contract-v1"
DEFAULT_WRITER = os.getenv("CONTENT_RENDER_QUEUE_WRITER_VERSION", "legacy_v1")
DEFAULT_CERT = os.getenv("CONTENT_RENDER_QUEUE_CERT_VERSION", "legacy_generation")


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def contract(writer_version: str, cert_version: str, source: str = "buffer") -> dict[str, Any]:
    if not writer_version.strip() or not cert_version.strip():
        raise ValueError("writer_version and cert_version are required")
    return {
        "schema": SCHEMA,
        "writer_version": writer_version.strip(),
        "certification_version": cert_version.strip(),
        "source": source,
        "created_at": _now(),
    }


# Markers only the canonical Writer V2.1 orchestrator puts on an ACCEPTED
# manifest. Their presence means the artifact carries V2.1 acceptance evidence.
V21_CERTIFICATION_MARKERS = ("_semantic_verified", "_v2_spoken_scene_count")


def looks_v21_certified(payload: Mapping[str, Any]) -> bool:
    """Pure. True when a manifest carries Writer V2.1 acceptance evidence."""
    if not isinstance(payload, Mapping):
        return False
    return any(payload.get(m) for m in V21_CERTIFICATION_MARKERS)


def stamp_manifest(payload: Mapping[str, Any], *, writer_version: str, cert_version: str, source: str = "buffer") -> dict[str, Any]:
    if not isinstance(payload, Mapping) or not isinstance(payload.get("scenes"), list):
        raise ValueError("not a render manifest")
    out = dict(payload)
    # A manifest with no contract yet is assumed to be pre-cutover inventory, so
    # the stamper labels it. That assumption is only safe while the artifact
    # shows no sign of being V2.1-certified. render.yml stamps the queue
    # immediately before REQUIRING the legacy label, so without this guard a
    # V2.1 manifest dropped in unstamped would be auto-blessed as legacy and
    # dequeued -- exactly the silent migration the contract exists to prevent.
    if not out.get("_factory_contract") and looks_v21_certified(out) and "v2" not in writer_version.lower():
        raise ValueError(
            f"refusing to stamp a Writer V2.1-certified manifest as {writer_version!r}: "
            "it carries V2.1 acceptance evidence and must be labelled by the lane that "
            "produced it, never relabelled as legacy inventory"
        )
    existing = out.get("_factory_contract")
    if existing:
        if not isinstance(existing, Mapping) or existing.get("schema") != SCHEMA:
            raise ValueError("unknown existing factory contract")
        # Never silently relabel a manifest generated by another Writer.
        if str(existing.get("writer_version") or "") != writer_version:
            raise ValueError("refusing to rewrite existing writer_version")
        return out
    out["_factory_contract"] = contract(writer_version, cert_version, source)
    return out


def stamp_file(path: str | Path, *, writer_version: str = DEFAULT_WRITER, cert_version: str = DEFAULT_CERT, source: str = "buffer") -> bool:
    p = Path(path)
    obj = json.loads(p.read_text(encoding="utf-8"))
    stamped = stamp_manifest(obj, writer_version=writer_version, cert_version=cert_version, source=source)
    if stamped == obj:
        return False
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(stamped, indent=2), encoding="utf-8")
    os.replace(tmp, p)
    return True


def stamp_queue(queue_dir: str | Path, *, writer_version: str = DEFAULT_WRITER, cert_version: str = DEFAULT_CERT) -> dict[str, Any]:
    root = Path(queue_dir)
    root.mkdir(parents=True, exist_ok=True)
    changed = 0
    checked = 0
    for p in sorted(root.glob("*.json")):
        checked += 1
        if stamp_file(p, writer_version=writer_version, cert_version=cert_version):
            changed += 1
    return {"checked": checked, "stamped": changed, "writer_version": writer_version, "certification_version": cert_version}


def compatibility(payload: Mapping[str, Any], *, required_writer: str, required_cert: str = "") -> tuple[bool, str]:
    c = payload.get("_factory_contract")
    if not isinstance(c, Mapping):
        return False, "unversioned manifest"
    if c.get("schema") != SCHEMA:
        return False, "unknown queue contract schema"
    if str(c.get("writer_version") or "") != required_writer:
        return False, f"writer version {c.get('writer_version')!r} != required {required_writer!r}"
    if required_cert and str(c.get("certification_version") or "") != required_cert:
        return False, f"certification version {c.get('certification_version')!r} != required {required_cert!r}"
    if not isinstance(payload.get("scenes"), list) or not payload.get("scenes"):
        return False, "manifest has no scenes"
    return True, "compatible"


def dequeue_compatible(
    queue_dir: str | Path,
    dest: str | Path,
    *,
    required_writer: str,
    required_cert: str = "",
    quarantine_dir: str | Path | None = None,
) -> tuple[int, dict[str, Any]]:
    root = Path(queue_dir)
    files = sorted(root.glob("*.json")) if root.exists() else []
    rejected: list[dict[str, str]] = []
    for src in files:
        try:
            obj = json.loads(src.read_text(encoding="utf-8"))
            if not isinstance(obj, Mapping):
                raise ValueError("queued JSON is not an object")
            ok, reason = compatibility(obj, required_writer=required_writer, required_cert=required_cert)
        except Exception as exc:
            ok, reason = False, f"malformed: {type(exc).__name__}: {exc}"
            obj = None
        if not ok:
            rejected.append({"file": src.name, "reason": reason})
            if quarantine_dir is not None:
                qroot = Path(quarantine_dir)
                qroot.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(qroot / src.name))
            continue
        out = Path(dest)
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp = out.with_suffix(out.suffix + ".tmp")
        tmp.write_text(json.dumps(obj, indent=2), encoding="utf-8")
        os.replace(tmp, out)
        src.unlink()
        return 0, {"selected": src.name, "rejected": rejected, "remaining": len(list(root.glob('*.json')))}
    return 3, {"selected": "", "rejected": rejected, "remaining": len(list(root.glob('*.json'))) if root.exists() else 0}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--queue-dir", default=f"queue_{os.getenv('PAGE', 'science')}")
    ap.add_argument("--stamp", action="store_true")
    ap.add_argument("--dequeue", metavar="DEST")
    ap.add_argument("--writer-version", default=DEFAULT_WRITER)
    ap.add_argument("--cert-version", default=DEFAULT_CERT)
    ap.add_argument("--required-writer", default=os.getenv("CONTENT_RENDER_REQUIRED_WRITER_VERSION", DEFAULT_WRITER))
    ap.add_argument("--required-cert", default=os.getenv("CONTENT_RENDER_REQUIRED_CERT_VERSION", ""))
    ap.add_argument("--quarantine-dir", default="")
    args = ap.parse_args(argv)
    try:
        if args.stamp:
            print(json.dumps(stamp_queue(args.queue_dir, writer_version=args.writer_version, cert_version=args.cert_version), indent=2))
            return 0
        if args.dequeue:
            rc, evidence = dequeue_compatible(
                args.queue_dir,
                args.dequeue,
                required_writer=args.required_writer,
                required_cert=args.required_cert,
                quarantine_dir=args.quarantine_dir or None,
            )
            print(json.dumps(evidence, indent=2))
            return rc
        ap.error("choose --stamp or --dequeue")
    except Exception as exc:
        print(f"QUEUE CONTRACT FAILED: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
